const COLOR_BAR_NUMERIC_POSITIVE = 'green'
const COLOR_BAR_NUMERIC_NEGATIVE = 'red'
const COLOR_BAR_BOOLEAN_TRUE = 'green'
const COLOR_BAR_BOOLEAN_FALSE = 'red'
const COLOR_BAR_ORDINAL = 'purple'

const COLOR_LINE_MEAN = 'blue'
const COLOR_LINE_OUTLIER = 'red'

const COLOR_BACKGROUND_NULL = 'lightgrey'
const COLOR_BACKGROUND_SELECTED = 'yellow'
const COLOR_BACKGROUND_UNSELECTED = 'white'
